import { ThemePreset } from "@/types/theme"

export const defaultPresets: Record<string, ThemePreset> = {
  neobrutal: {
    label: "Neobrutalism",
    createdAt: "2025-11-06",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#ffffff",
        "card-foreground": "#000000",
        popover: "#ffffff",
        "popover-foreground": "#000000",
        primary: "#ff3333",
        "primary-foreground": "#ffffff",
        secondary: "#ffff00",
        "secondary-foreground": "#000000",
        muted: "#f0f0f0",
        "muted-foreground": "#333333",
        accent: "#0066ff",
        "accent-foreground": "#ffffff",
        destructive: "#000000",
        "destructive-foreground": "#ffffff",
        border: "#000000",
        input: "#000000",
        ring: "#ff3333",
        "chart-1": "#ff3333",
        "chart-2": "#ffff00",
        "chart-3": "#0066ff",
        "chart-4": "#00cc00",
        "chart-5": "#cc00cc",
        sidebar: "#f0f0f0",
        "sidebar-foreground": "#000000",
        "sidebar-primary": "#ff3333",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#0066ff",
        "sidebar-accent-foreground": "#ffffff",
        "sidebar-border": "#000000",
        "sidebar-ring": "#ff3333",
        "font-sans": "DM Sans, sans-serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "Space Mono, monospace",
        radius: "0px",
        "shadow-color": "#000000",
        "shadow-opacity": "1",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "4px",
        "shadow-offset-y": "4px",
      },
      dark: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#333333",
        "card-foreground": "#ffffff",
        popover: "#333333",
        "popover-foreground": "#ffffff",
        primary: "#ff6666",
        "primary-foreground": "#000000",
        secondary: "#ffff33",
        "secondary-foreground": "#000000",
        muted: "#333333",
        "muted-foreground": "#cccccc",
        accent: "#3399ff",
        "accent-foreground": "#000000",
        destructive: "#ffffff",
        "destructive-foreground": "#000000",
        border: "#ffffff",
        input: "#ffffff",
        ring: "#ff6666",
        "chart-1": "#ff6666",
        "chart-2": "#ffff33",
        "chart-3": "#3399ff",
        "chart-4": "#33cc33",
        "chart-5": "#cc33cc",
        sidebar: "#000000",
        "sidebar-foreground": "#ffffff",
        "sidebar-primary": "#ff6666",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#3399ff",
        "sidebar-accent-foreground": "#000000",
        "sidebar-border": "#ffffff",
        "sidebar-ring": "#ff6666",
        "font-sans": "DM Sans, sans-serif",
        "font-serif": "Source Serif 4, serif",
        "font-mono": "Space Mono, monospace",
        radius: "0px",
        "shadow-color": "#000000",
        "shadow-opacity": "1",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "4px",
        "shadow-offset-y": "4px",
      },
    },
  },
  minimal: {
    label: "Minimal",
    createdAt: "2025-11-06",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#0a0a0a",
        card: "#ffffff",
        "card-foreground": "#0a0a0a",
        popover: "#ffffff",
        "popover-foreground": "#0a0a0a",
        primary: "#171717",
        "primary-foreground": "#fafafa",
        secondary: "#f5f5f5",
        "secondary-foreground": "#171717",
        muted: "#f5f5f5",
        "muted-foreground": "#737373",
        accent: "#f5f5f5",
        "accent-foreground": "#171717",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#e5e5e5",
        input: "#e5e5e5",
        ring: "#171717",
        "chart-1": "#171717",
        "chart-2": "#737373",
        "chart-3": "#a3a3a3",
        "chart-4": "#d4d4d4",
        "chart-5": "#e5e5e5",
        sidebar: "#fafafa",
        "sidebar-foreground": "#0a0a0a",
        "sidebar-primary": "#171717",
        "sidebar-primary-foreground": "#fafafa",
        "sidebar-accent": "#f5f5f5",
        "sidebar-accent-foreground": "#171717",
        "sidebar-border": "#e5e5e5",
        "sidebar-ring": "#171717",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.05",
        "shadow-blur": "10px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "1px",
      },
      dark: {
        background: "#0a0a0a",
        foreground: "#fafafa",
        card: "#171717",
        "card-foreground": "#fafafa",
        popover: "#171717",
        "popover-foreground": "#fafafa",
        primary: "#fafafa",
        "primary-foreground": "#0a0a0a",
        secondary: "#262626",
        "secondary-foreground": "#fafafa",
        muted: "#262626",
        "muted-foreground": "#a3a3a3",
        accent: "#262626",
        "accent-foreground": "#fafafa",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#262626",
        input: "#262626",
        ring: "#fafafa",
        "chart-1": "#fafafa",
        "chart-2": "#a3a3a3",
        "chart-3": "#737373",
        "chart-4": "#525252",
        "chart-5": "#404040",
        sidebar: "#0a0a0a",
        "sidebar-foreground": "#fafafa",
        "sidebar-primary": "#fafafa",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#262626",
        "sidebar-accent-foreground": "#fafafa",
        "sidebar-border": "#262626",
        "sidebar-ring": "#fafafa",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "JetBrains Mono, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.5",
        "shadow-blur": "20px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
      },
    },
  },
  slate: {
    label: "Slate",
    createdAt: "2025-11-06",
    styles: {
      light: {
        background: "#f8fafc",
        foreground: "#0f172a",
        card: "#ffffff",
        "card-foreground": "#0f172a",
        popover: "#ffffff",
        "popover-foreground": "#0f172a",
        primary: "#0f172a",
        "primary-foreground": "#f8fafc",
        secondary: "#f1f5f9",
        "secondary-foreground": "#0f172a",
        muted: "#f1f5f9",
        "muted-foreground": "#64748b",
        accent: "#e2e8f0",
        "accent-foreground": "#0f172a",
        destructive: "#dc2626",
        "destructive-foreground": "#f8fafc",
        border: "#e2e8f0",
        input: "#e2e8f0",
        ring: "#64748b",
        "chart-1": "#0f172a",
        "chart-2": "#475569",
        "chart-3": "#64748b",
        "chart-4": "#94a3b8",
        "chart-5": "#cbd5e1",
        sidebar: "#f8fafc",
        "sidebar-foreground": "#0f172a",
        "sidebar-primary": "#0f172a",
        "sidebar-primary-foreground": "#f8fafc",
        "sidebar-accent": "#f1f5f9",
        "sidebar-accent-foreground": "#0f172a",
        "sidebar-border": "#e2e8f0",
        "sidebar-ring": "#64748b",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Roboto Mono, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(215 25% 27%)",
        "shadow-opacity": "0.08",
        "shadow-blur": "8px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
      },
      dark: {
        background: "#0f172a",
        foreground: "#f1f5f9",
        card: "#1e293b",
        "card-foreground": "#f1f5f9",
        popover: "#1e293b",
        "popover-foreground": "#f1f5f9",
        primary: "#f1f5f9",
        "primary-foreground": "#0f172a",
        secondary: "#334155",
        "secondary-foreground": "#f1f5f9",
        muted: "#334155",
        "muted-foreground": "#94a3b8",
        accent: "#334155",
        "accent-foreground": "#f1f5f9",
        destructive: "#dc2626",
        "destructive-foreground": "#f1f5f9",
        border: "#334155",
        input: "#334155",
        ring: "#94a3b8",
        "chart-1": "#f1f5f9",
        "chart-2": "#cbd5e1",
        "chart-3": "#94a3b8",
        "chart-4": "#64748b",
        "chart-5": "#475569",
        sidebar: "#0f172a",
        "sidebar-foreground": "#f1f5f9",
        "sidebar-primary": "#f1f5f9",
        "sidebar-primary-foreground": "#0f172a",
        "sidebar-accent": "#334155",
        "sidebar-accent-foreground": "#f1f5f9",
        "sidebar-border": "#334155",
        "sidebar-ring": "#94a3b8",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Roboto Mono, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(215 25% 27%)",
        "shadow-opacity": "0.5",
        "shadow-blur": "16px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
      },
    },
  },
  ocean: {
    label: "Ocean",
    createdAt: "2025-11-06",
    styles: {
      light: {
        background: "#f0f9ff",
        foreground: "#0c4a6e",
        card: "#ffffff",
        "card-foreground": "#0c4a6e",
        popover: "#ffffff",
        "popover-foreground": "#0c4a6e",
        primary: "#0284c7",
        "primary-foreground": "#f0f9ff",
        secondary: "#e0f2fe",
        "secondary-foreground": "#075985",
        muted: "#e0f2fe",
        "muted-foreground": "#0369a1",
        accent: "#bae6fd",
        "accent-foreground": "#075985",
        destructive: "#dc2626",
        "destructive-foreground": "#f0f9ff",
        border: "#bae6fd",
        input: "#e0f2fe",
        ring: "#0284c7",
        "chart-1": "#0284c7",
        "chart-2": "#0ea5e9",
        "chart-3": "#38bdf8",
        "chart-4": "#7dd3fc",
        "chart-5": "#bae6fd",
        sidebar: "#f0f9ff",
        "sidebar-foreground": "#0c4a6e",
        "sidebar-primary": "#0284c7",
        "sidebar-primary-foreground": "#f0f9ff",
        "sidebar-accent": "#e0f2fe",
        "sidebar-accent-foreground": "#075985",
        "sidebar-border": "#bae6fd",
        "sidebar-ring": "#0284c7",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
        radius: "0.75rem",
        "shadow-color": "hsl(199 89% 48%)",
        "shadow-opacity": "0.1",
        "shadow-blur": "12px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
      },
      dark: {
        background: "#082f49",
        foreground: "#e0f2fe",
        card: "#0c4a6e",
        "card-foreground": "#e0f2fe",
        popover: "#0c4a6e",
        "popover-foreground": "#e0f2fe",
        primary: "#38bdf8",
        "primary-foreground": "#082f49",
        secondary: "#075985",
        "secondary-foreground": "#e0f2fe",
        muted: "#075985",
        "muted-foreground": "#7dd3fc",
        accent: "#0369a1",
        "accent-foreground": "#e0f2fe",
        destructive: "#ef4444",
        "destructive-foreground": "#e0f2fe",
        border: "#0369a1",
        input: "#075985",
        ring: "#38bdf8",
        "chart-1": "#38bdf8",
        "chart-2": "#0ea5e9",
        "chart-3": "#0284c7",
        "chart-4": "#0369a1",
        "chart-5": "#075985",
        sidebar: "#082f49",
        "sidebar-foreground": "#e0f2fe",
        "sidebar-primary": "#38bdf8",
        "sidebar-primary-foreground": "#082f49",
        "sidebar-accent": "#075985",
        "sidebar-accent-foreground": "#e0f2fe",
        "sidebar-border": "#0369a1",
        "sidebar-ring": "#38bdf8",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
        radius: "0.75rem",
        "shadow-color": "hsl(199 89% 48%)",
        "shadow-opacity": "0.3",
        "shadow-blur": "16px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
      },
    },
  },
  graphite: {
    label: "Graphite",
    createdAt: "2025-04-17",
    styles: {
      light: {
        background: "#f0f0f0",
        foreground: "#333333",
        card: "#f5f5f5",
        "card-foreground": "#333333",
        popover: "#f5f5f5",
        "popover-foreground": "#333333",
        primary: "#606060",
        "primary-foreground": "#ffffff",
        secondary: "#e0e0e0",
        "secondary-foreground": "#333333",
        muted: "#d9d9d9",
        "muted-foreground": "#666666",
        accent: "#c0c0c0",
        "accent-foreground": "#333333",
        destructive: "#cc3333",
        "destructive-foreground": "#ffffff",
        border: "#d0d0d0",
        input: "#e0e0e0",
        ring: "#606060",
        "chart-1": "#606060",
        "chart-2": "#476666",
        "chart-3": "#909090",
        "chart-4": "#a8a8a8",
        "chart-5": "#c0c0c0",
        sidebar: "#eaeaea",
        "sidebar-foreground": "#333333",
        "sidebar-primary": "#606060",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#c0c0c0",
        "sidebar-accent-foreground": "#333333",
        "sidebar-border": "#d0d0d0",
        "sidebar-ring": "#606060",
        "font-sans": "Montserrat, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
        radius: "0.35rem",
        "shadow-color": "hsl(0 0% 20% / 0.1)",
        "shadow-opacity": "0.15",
        "shadow-blur": "0px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "2px",
      },
      dark: {
        background: "#1a1a1a",
        foreground: "#d9d9d9",
        card: "#202020",
        "card-foreground": "#d9d9d9",
        popover: "#202020",
        "popover-foreground": "#d9d9d9",
        primary: "#a0a0a0",
        "primary-foreground": "#1a1a1a",
        secondary: "#303030",
        "secondary-foreground": "#d9d9d9",
        muted: "#2a2a2a",
        "muted-foreground": "#808080",
        accent: "#404040",
        "accent-foreground": "#d9d9d9",
        destructive: "#e06666",
        "destructive-foreground": "#ffffff",
        border: "#353535",
        input: "#303030",
        ring: "#a0a0a0",
        "chart-1": "#a0a0a0",
        "chart-2": "#7e9ca0",
        "chart-3": "#707070",
        "chart-4": "#585858",
        "chart-5": "#404040",
        sidebar: "#1f1f1f",
        "sidebar-foreground": "#d9d9d9",
        "sidebar-primary": "#a0a0a0",
        "sidebar-primary-foreground": "#1a1a1a",
        "sidebar-accent": "#404040",
        "sidebar-accent-foreground": "#d9d9d9",
        "sidebar-border": "#353535",
        "sidebar-ring": "#a0a0a0",
        "font-sans": "Inter, sans-serif",
        "font-serif": "Georgia, serif",
        "font-mono": "Fira Code, monospace",
      },
    },
  },
  "vintage-paper": {
    label: "Vintage Paper",
    styles: {
      light: {
        background: "#f5f1e6",
        foreground: "#4a3f35",
        card: "#fffcf5",
        "card-foreground": "#4a3f35",
        popover: "#fffcf5",
        "popover-foreground": "#4a3f35",
        primary: "#a67c52",
        "primary-foreground": "#ffffff",
        secondary: "#e2d8c3",
        "secondary-foreground": "#5c4d3f",
        muted: "#ece5d8",
        "muted-foreground": "#7d6b56",
        accent: "#d4c8aa",
        "accent-foreground": "#4a3f35",
        destructive: "#b54a35",
        "destructive-foreground": "#ffffff",
        border: "#dbd0ba",
        input: "#dbd0ba",
        ring: "#a67c52",
        "chart-1": "#a67c52",
        "chart-2": "#8d6e4c",
        "chart-3": "#735a3a",
        "chart-4": "#b3906f",
        "chart-5": "#c0a080",
        radius: "0.25rem",
        sidebar: "#ece5d8",
        "sidebar-foreground": "#4a3f35",
        "sidebar-primary": "#a67c52",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#d4c8aa",
        "sidebar-accent-foreground": "#4a3f35",
        "sidebar-border": "#dbd0ba",
        "sidebar-ring": "#a67c52",
        "font-sans": "Libre Baskerville, serif",
        "font-serif": "Lora, serif",
        "font-mono": "IBM Plex Mono, monospace",
        "shadow-color": "hsl(28 13% 20%)",
        "shadow-opacity": "0.12",
        "shadow-blur": "5px",
        "shadow-spread": "0px",
        "shadow-offset-x": "2px",
        "shadow-offset-y": "3px",
      },
      dark: {
        background: "#2d2621",
        foreground: "#ece5d8",
        card: "#3a322c",
        "card-foreground": "#ece5d8",
        popover: "#3a322c",
        "popover-foreground": "#ece5d8",
        primary: "#c0a080",
        "primary-foreground": "#2d2621",
        secondary: "#4a4039",
        "secondary-foreground": "#ece5d8",
        muted: "#3a322c",
        "muted-foreground": "#c5bcac",
        accent: "#59493e",
        "accent-foreground": "#ece5d8",
        destructive: "#b54a35",
        "destructive-foreground": "#ffffff",
        border: "#4a4039",
        input: "#4a4039",
        ring: "#c0a080",
        "chart-1": "#c0a080",
        "chart-2": "#b3906f",
        "chart-3": "#a67c52",
        "chart-4": "#8d6e4c",
        "chart-5": "#735a3a",
        radius: "0.25rem",
        sidebar: "#2d2621",
        "sidebar-foreground": "#ece5d8",
        "sidebar-primary": "#c0a080",
        "sidebar-primary-foreground": "#2d2621",
        "sidebar-accent": "#59493e",
        "sidebar-accent-foreground": "#ece5d8",
        "sidebar-border": "#4a4039",
        "sidebar-ring": "#c0a080",
      },
    },
  },
  "starry-night": {
    label: "Starry Night",
    createdAt: "2025-04-16",
    styles: {
      light: {
        background: "#f5f7fa",
        foreground: "#1a2238",
        card: "#e3eaf2",
        "card-foreground": "#1a2238",
        popover: "#fffbe6",
        "popover-foreground": "#1a2238",
        primary: "#3a5ba0",
        "primary-foreground": "#fffbe6",
        secondary: "#f7c873",
        "secondary-foreground": "#1a2238",
        muted: "#e5e5df",
        "muted-foreground": "#3a5ba0",
        accent: "#6ea3c1",
        "accent-foreground": "#fffbe6",
        destructive: "#2d1e2f",
        "destructive-foreground": "#fffbe6",
        border: "#b0b8c1",
        input: "#6ea3c1",
        ring: "#f7c873",
        "chart-1": "#3a5ba0",
        "chart-2": "#f7c873",
        "chart-3": "#6ea3c1",
        "chart-4": "#b0b8c1",
        "chart-5": "#2d1e2f",
        sidebar: "#e3eaf2",
        "sidebar-foreground": "#1a2238",
        "sidebar-primary": "#3a5ba0",
        "sidebar-primary-foreground": "#fffbe6",
        "sidebar-accent": "#f7c873",
        "sidebar-accent-foreground": "#1a2238",
        "sidebar-border": "#b0b8c1",
        "sidebar-ring": "#f7c873",
        "font-sans": "Libre Baskerville, serif",
        radius: "0.5rem",
      },
      dark: {
        background: "#181a24",
        foreground: "#e6eaf3",
        card: "#23243a",
        "card-foreground": "#e6eaf3",
        popover: "#23243a",
        "popover-foreground": "#ffe066",
        primary: "#3a5ba0",
        "primary-foreground": "#ffe066",
        secondary: "#ffe066",
        "secondary-foreground": "#23243a",
        muted: "#23243a",
        "muted-foreground": "#7a88a1",
        accent: "#bccdf0",
        "accent-foreground": "#181a24",
        destructive: "#a04a6c",
        "destructive-foreground": "#ffe066",
        border: "#2d2e3e",
        input: "#3a5ba0",
        ring: "#ffe066",
        "chart-1": "#3a5ba0",
        "chart-2": "#ffe066",
        "chart-3": "#6ea3c1",
        "chart-4": "#7a88a1",
        "chart-5": "#a04a6c",
        sidebar: "#23243a",
        "sidebar-foreground": "#e6eaf3",
        "sidebar-primary": "#3a5ba0",
        "sidebar-primary-foreground": "#ffe066",
        "sidebar-accent": "#ffe066",
        "sidebar-accent-foreground": "#23243a",
        "sidebar-border": "#2d2e3e",
        "sidebar-ring": "#ffe066",
        radius: "0.5rem",
      },
    },
  },
  "v0-dark": {
    label: "v0.dev Dark",
    createdAt: "2025-11-08",
    styles: {
      light: {
        background: "#ffffff",
        foreground: "#0a0a0a",
        card: "#ffffff",
        "card-foreground": "#0a0a0a",
        popover: "#ffffff",
        "popover-foreground": "#0a0a0a",
        primary: "#171717",
        "primary-foreground": "#fafafa",
        secondary: "#f5f5f5",
        "secondary-foreground": "#171717",
        muted: "#f5f5f5",
        "muted-foreground": "#737373",
        accent: "#f5f5f5",
        "accent-foreground": "#171717",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#e5e5e5",
        input: "#e5e5e5",
        ring: "#171717",
        "chart-1": "#171717",
        "chart-2": "#737373",
        "chart-3": "#a3a3a3",
        "chart-4": "#d4d4d4",
        "chart-5": "#e5e5e5",
        sidebar: "#fafafa",
        "sidebar-foreground": "#0a0a0a",
        "sidebar-primary": "#171717",
        "sidebar-primary-foreground": "#fafafa",
        "sidebar-accent": "#f5f5f5",
        "sidebar-accent-foreground": "#171717",
        "sidebar-border": "#e5e5e5",
        "sidebar-ring": "#171717",
        "font-sans": "Geist, sans-serif",
        "font-serif": "Geist, serif",
        "font-mono": "Geist Mono, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.05",
        "shadow-blur": "10px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "1px",
      },
      dark: {
        background: "#0a0a0a",
        foreground: "#ededed",
        card: "#0a0a0a",
        "card-foreground": "#ededed",
        popover: "#0a0a0a",
        "popover-foreground": "#ededed",
        primary: "#fafafa",
        "primary-foreground": "#0a0a0a",
        secondary: "#171717",
        "secondary-foreground": "#fafafa",
        muted: "#171717",
        "muted-foreground": "#a1a1a1",
        accent: "#262626",
        "accent-foreground": "#fafafa",
        destructive: "#ef4444",
        "destructive-foreground": "#fafafa",
        border: "#262626",
        input: "#262626",
        ring: "#525252",
        "chart-1": "#fafafa",
        "chart-2": "#a1a1a1",
        "chart-3": "#737373",
        "chart-4": "#525252",
        "chart-5": "#404040",
        sidebar: "#0a0a0a",
        "sidebar-foreground": "#ededed",
        "sidebar-primary": "#fafafa",
        "sidebar-primary-foreground": "#0a0a0a",
        "sidebar-accent": "#262626",
        "sidebar-accent-foreground": "#fafafa",
        "sidebar-border": "#1a1a1a",
        "sidebar-ring": "#525252",
        "font-sans": "Geist, sans-serif",
        "font-serif": "Geist, serif",
        "font-mono": "Geist Mono, monospace",
        radius: "0.5rem",
        "shadow-color": "hsl(0 0% 0%)",
        "shadow-opacity": "0.5",
        "shadow-blur": "20px",
        "shadow-spread": "0px",
        "shadow-offset-x": "0px",
        "shadow-offset-y": "4px",
      },
    },
  },
}
