import { saveSandboxFiles } from "@/lib/db/services/sandbox.service"
import type { Sandbox } from "@vercel/sandbox"
import type { UIMessage, UIMessageStreamWriter } from "ai"
import type { DataPart } from "../../messages/data-parts"
import { getRichError } from "../get-rich-error"
import type { File } from "./get-contents"

interface Params {
  sandbox: Sandbox
  toolCallId: string
  writer: UIMessageStreamWriter<UIMessage<never, DataPart>>
}

export function getWriteFiles({ sandbox, toolCallId, writer }: Params) {
  return async function writeFiles(params: {
    written: string[]
    files: File[]
    paths: string[]
  }) {
    const paths = params.written.concat(params.files.map((file) => file.path))
    writer.write({
      id: toolCallId,
      type: "data-generating-files",
      data: { paths, status: "uploading" },
    })

    try {
      await sandbox.writeFiles(
        params.files.map((file) => ({
          content: Buffer.from(file.content, "utf8"),
          path: file.path,
        }))
      )

      // Persist files to database
      try {
        await saveSandboxFiles(
          sandbox.sandboxId,
          params.files.map((file) => ({
            path: file.path,
            content: file.content,
            isGenerated: true, // Files generated by AI
          }))
        )
      } catch (dbError) {
        console.error("Failed to persist files to database:", dbError)
        // Continue even if DB save fails - don't block user
      }
    } catch (error) {
      const richError = getRichError({
        action: "write files to sandbox",
        args: params,
        error,
      })

      writer.write({
        id: toolCallId,
        type: "data-generating-files",
        data: {
          error: richError.error,
          status: "error",
          paths: params.paths,
        },
      })

      return richError.message
    }

    writer.write({
      id: toolCallId,
      type: "data-generating-files",
      data: { paths, status: "uploaded" },
    })
  }
}
